export const LABELS = {
  appName: 'ZoneRide',
  tagline: 'Local Delivery, Your Way',
  customer: 'Customer',
  rider: 'Rider',
  shop: 'Shop',
  roleSelectionTitle: 'Choose Your Role',
  roleSelectionSubtitle: 'Select how you want to use ZoneRide',
  customerDescription: 'Order deliveries and discover local services',
  riderDescription: 'Accept delivery requests and earn',
  shopDescription: 'Manage orders and connect with riders',
  loginTitle: 'Welcome to ZoneRide',
  loginSubtitle: 'Enter your phone number to continue',
  phoneLabel: 'Phone Number',
  phonePlaceholder: 'Enter phone number',
  otpLabel: 'OTP Code',
  otpPlaceholder: 'Enter 4-digit OTP',
  sendOtp: 'Send OTP',
  verifyOtp: 'Verify OTP',
  googleSignIn: 'Sign in with Google',
  orDivider: 'OR',
  areaSelectionTitle: 'Select Your Area',
  areaSelectionSubtitle: 'Choose your operating zone',
  continueButton: 'Continue',
  deliveryMan: 'Delivery Man',
  shops: 'Shops',
  noRidersInArea: 'No riders available in this area',
  noShopsInArea: 'No shops found in this area',
  call: 'Call',
  chat: 'Chat',
  subscribe: 'Subscribe',
  unsubscribe: 'Unsubscribe',
  block: 'Block',
  requestDelivery: 'Request Delivery',
  viewMenu: 'View Menu',
  accept: 'Accept',
  reject: 'Reject',
  submit: 'Submit',
  cancel: 'Cancel',
  assignRider: 'Assign Rider',
  requestFormTitle: 'New Delivery Request',
  itemDescription: 'Item Description',
  itemDescriptionPlaceholder: 'What needs to be delivered?',
  pickupLocation: 'Pickup Location',
  pickupPlaceholder: 'Enter pickup address',
  deliveryLocation: 'Delivery Location',
  deliveryPlaceholder: 'Enter delivery address',
  deliveryTime: 'Delivery Time',
  deliveryFee: 'Delivery Fee (BDT)',
  feePlaceholder: 'Enter amount',
  requestPosted: 'Request posted successfully!',
  timeAsap: 'As soon as possible',
  time30min: 'Within 30 minutes',
  time1hour: 'Within 1 hour',
  time2hours: 'Within 2 hours',
  timeScheduled: 'Schedule for later',
  trackingTitle: 'Request Tracking',
  statusPosted: 'Posted',
  statusAccepted: 'Accepted',
  statusPicked: 'Picked',
  statusOnTheWay: 'On The Way',
  statusDelivered: 'Delivered',
  statusCompleted: 'Completed',
  statusRejected: 'Rejected',
  riderRequestsTitle: 'Incoming Requests',
  deliveryDetailsTitle: 'Delivery Details',
  earningsTitle: 'Earnings',
  totalEarnings: 'Total Earnings',
  recentDeliveries: 'Recent Deliveries',
  noRequests: 'No pending requests',
  riderProfileTitle: 'Rider Profile',
  availability: 'Availability',
  active: 'Active',
  inactive: 'Inactive',
  vehicleType: 'Vehicle Type',
  servedAreas: 'Served Areas',
  markPicked: 'Mark as Picked',
  markOnTheWay: 'Mark On The Way',
  markDelivered: 'Mark as Delivered',
  shopOrdersTitle: 'Orders',
  orderDetailsTitle: 'Order Details',
  shopRidersTitle: 'Manage Riders',
  shopMenuTitle: 'Menu Gallery',
  shopProfileTitle: 'Shop Profile',
  noOrders: 'No orders yet',
  noMenuItems: 'No menu items yet',
  uploadImage: 'Upload Image',
  openStatus: 'Open',
  closedStatus: 'Closed',
  workingHours: 'Working Hours',
  customerProfileTitle: 'Profile',
  name: 'Name',
  phone: 'Phone',
  defaultAddress: 'Default Address',
  editAddress: 'Edit Address',
  addressPlaceholder: 'Enter your default delivery address',
  addressSaved: 'Default address updated!',
  favoriteRiders: 'Favorite Riders',
  deliveryHistory: 'Delivery History',
  noHistory: 'No delivery history yet',
  chatsTitle: 'Chats',
  noChats: 'No conversations yet',
  typeMessage: 'Type a message...',
  send: 'Send',
  notificationsTitle: 'Notifications',
  noNotifications: 'No notifications yet',
  markAllRead: 'Mark all as read',
  baseFee: 'Base Fee',
  platformCommission: 'Platform Commission',
  deliveryCharge: 'Delivery Charge',
  total: 'Total',
  loading: 'Loading...',
  retry: 'Retry',
  back: 'Back',
  save: 'Save',
  edit: 'Edit',
  delete: 'Delete',
  confirm: 'Confirm',
  rating: 'Rating',
};

export const DELIVERY_TIME_OPTIONS = [
  LABELS.timeAsap,
  LABELS.time30min,
  LABELS.time1hour,
  LABELS.time2hours,
  LABELS.timeScheduled,
];

export const DELIVERY_STATUS_STEPS = [
  LABELS.statusPosted,
  LABELS.statusAccepted,
  LABELS.statusPicked,
  LABELS.statusOnTheWay,
  LABELS.statusDelivered,
  LABELS.statusCompleted,
];
